command_timeout = 1000

[aws]
disabled = false

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[directory]
truncation_length = 10

[docker_context]
disabled = true

[git_branch]

[git_commit]

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = false

[git_status]

[kubernetes]
disabled = true

[package]

[shell]
disabled = false

